### ISSUE TITLE
[SOLVED] Cannot Install Look-and-Feel Theme (frameworkintegration 5.58.1-1 bug)

### ISSUE THREAD

**Issue by vladacr** [Mrcuve0/Aritim-Light#2]
I like the theme a lot, but I am unable to install it on my current system. All I get is an error. 
```
kpackagetool5 -i Aritim-Light-KDE-master.zip 
couldn't find knsrc file for "wallpaper.knsrc"
Error: Installation of /home/vlad/Stažené/Aritim-Light-KDE-master.zip failed: Could not install dependency: 'kns://wallpaper.knsrc/api.kde-look.org/1291140'
```
There is no wallpaper.knsrc on my system. Where or how can I fix this?

Attempting installation using the "System Settings" --> "Workspace Theme" --> "Download and new themes" shows the the theme is installed, even if it actually isn't. I was able to use the colour scheme, though.

System:
OS: Manjaro Linux x86_64 
Host: ThinkPad T420 
Kernel: 5.0.14-rt9-MANJARO 
Shell: bash 5.0.7 
DE: KDE 
WM: KWin 
WM Theme: Breezemite 
CPU: Intel i5-2430M (4) @ 3.000GHz

**Comment by FriederHannenheim** [comment]
Hi there, I'm still facing this issue with frameworkintegration-5.57.0-1 installed. 
`couldn't find knsrc file for "colorschemes.knsrc"
Error: Installation of /home/fried/Downloads/Dracula.tar.xz failed: Could not install dependency: 'kns://colorschemes.knsrc/api.kde-look.org/1370679'
`

**Comment by Mrcuve0** [comment]
Hi! You should definitely try to upgrade your KDE Frameworks package, on Opensuse Tumbleweed I'm actually @ 5.83.0. Or try to follow the above discussion and see if you have this file `colorschemes.knsrc` in `/etc/xdc` and try to solve in other ways.

Also, you are trying to install [Dracula-KDE](https://store.kde.org/p/1370679) made by eliverlara, you should try contacting him for this kind of issues, as this is not the right repo

**Comment by legend-zeratul** [comment]
Hi, the issue is still open. Manjaro-KDE - both 5.57 and 5.83 seem to have an error downloading/installing themes. Its NOT a problem with the theme itself - subsequent attempts seem to work, and its NOT specific to a single theme.

**Comment by Mrcuve0** [comment]
Thanks for the feedback! I just saw a thread on reddit reporting the issue as well. Let's hope they'll fix it soon!
