### ISSUE TITLE
Aritim-light doen't install correctly from KDE installer

### ISSUE THREAD

**Issue by Sagebati** [Mrcuve0/Aritim-Light#3]
**Describe the bug**
When you try to install the theme from KDE, the theme doesn't install correctly.

**Expected behavior**
Install the theme like Aritim-Dark who installs perfectly.

**Screenshots**
![image](https://user-images.githubusercontent.com/10544280/74327336-4a910680-4d8c-11ea-9c8a-d4a53c001f9d.png)

**Desktop (additional informations):**
Manjaro KDE.

 - KDE Plasma Version: 5.17.5
 - KDE Frameworks Version: 5.66

**Additional context**
The size of the theme in the KDE installer is ~300Ko But in opendesktop is 1.13 MB
![image](https://user-images.githubusercontent.com/10544280/74326879-78298000-4d8b-11ea-8d56-d8b1579fb53e.png)

**Comment by Mrcuve0** [comment]
Thank you for your feedback! As for now this is the best issue I received here on GH, really complete :smile: 

So, speaking of the bug, I fired up my KDE Neon VM (a quite old version, with KDE 5.14.3) and tried installing the theme and everything works flawlessly:
![Screenshot_20200212_125951](https://user-images.githubusercontent.com/36898760/74333122-91382e00-4d97-11ea-81cc-ea6b577ba1d4.png)

I also tried uninstalling my version on my everyday laptop ( I have the exact same distro and versions as you) and reinstalling it from the System Settings and again, everything is fine.

I finally took a look on opendesktop looking for the filesize and I cannot find a package with 1.13MB, below you can see all the updates I made on the package and they are all approximately the same size:

![Screenshot_20200212_130610](https://user-images.githubusercontent.com/36898760/74333556-75815780-4d98-11ea-86bb-18184e1c7c5e.png)

(Don't mind the 3MB+ packages: in those old versions I was also uploading some Screenshots that I decided to remove then)

I'm sorry that I can't reproduce the issue, I'll download an updated Manjaro KDE ISO and see if I can obtain the same issue. 
As for now you may simply want to install the lacking component: in System Settings, go to `Application Style` --> `Window Decorations` --> `Get New Window Decorations` and searching for Aritim-Light.
(You can also try [Sierra Brezze Window Decorations](https://github.com/ishovkun/SierraBreeze), that I personally prefer over Aurorae ones.

Or, you can try downloading older packages fromt the above list and try to install them using the command `kpackagetool5 -i zipName.zip` (after the installation you'll need to apply it from System Settings)

**Comment by Sagebati** [comment]
Thanks for your reactivity, and your work.
First installing the Windows decorations did the trick. I think my computer had a bug when installing the theme it only installed the theme and not the Windows decoration , colors etc.. Your other theme (dark version) installed all automatically. Maybe it's just my computer.

There is the link with the 1MB package :
https://www.pling.com/p/1318993/

You can close the issue. Thanks you !

**Comment by Mrcuve0** [comment]
The package you linked is the component that handles the panels like the one on top along with translucency and panel icons, so it is a different component (which is, however, downloaded as a dependency when you download the "look-and-feel / Global Theme" one).

Glad everything worked out! I'll test again with the new ISO and see if the issue happen.

PS: If you have an account on opendesktop, you may want to leave a rating on my theme at the pages like the one you linked in your last message! It means a lot to me, thanks!
