### ISSUE TITLE
Dolphin view

### ISSUE THREAD

**Issue by PrzemekSkw** [Mrcuve0/Aritim-Light#9]
**Describe the bug**
My Dolphin window don't look like in the screenschots. Blur is only on left panel.
![Screenshot_20210926_203734](https://user-images.githubusercontent.com/25219988/134820179-990469ef-a78c-46ea-b407-1e2b22271691.png)

**To Reproduce**
- set Global Aritim Theme
- set Lightly as Application Look
- there's Transparent Dolphin view checked in Lightly look Manager [Fremes Tab]

**Desktop (additional informations):**
 - OS: Reborn OS [KDE, Archlinux], AMD Ryzen5, Radeon Vega, 2160X1440 resolution, 60Hz, Global scling 100%, 
 - Kernel - 5.14.7-arch1-1

(if you are using KDE)
 - KDE Plasma Version: 5.22.5
 - KDE Frameworks Version: 5.86.0
 - Qt version: 5.15.2

Regards,
Przemek

**Comment by Mrcuve0** [comment]
Hi Przemek!

In the case of the top bar (the one with "go back" and "go forward" buttons on the top left corner) I believe you only have to set a correct value of transparency and blur. I post here my configurations (search `Application Style` in Settings and change Lightly settings)
![Screenshot_20210927_085915](https://user-images.githubusercontent.com/36898760/134859529-de240f74-1675-4fef-915e-a0222594f4ad.png)

For the window frame (close, minimize and maximize buttons), you need to change `Window Decorations` and select Lightly.
No further settings are needed in this case.

Let me now if this solves your problem!

**Comment by PrzemekSkw** [comment]
Thanks, I change everything to lighty theme not Aritim-light and now it's OK.
Regards.
